### ISSUE TITLE
Vuepress 1.* support

### ISSUE THREAD

**Issue by adelholtz** [alexander-heimbuch/vuepress-theme-millidocs#6]
Hi

for vuepress 1.* your package.json is missing the "main" property.
``
{
"main": "enhanceApp.js"
}
``

tried to fork and put out a pull request but i am not really sure about your branch structure.

**Comment by alexander-heimbuch** [comment]
Hey,
thanks for the feedback 👍 , simply put a PR against the master. I will create a new version once it's merged :)

**Comment by alexander-heimbuch** [comment]
published `0.5.4` with changes from your PR. Thanks for the contribution!
